version: '3'
services:
  app:
    container_name: crud_app
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AccountCrudDatabase
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  api:
  db_data: